"""esquema inicial: 19 tabelas

Revision ID: 5ab620c1b4d4
Revises: 
Create Date: 2026-09-22 21:39:04.640408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ab620c1b4d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'uf', name='uq_cidades_nome_uf')
    )
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissoes_codigo'), 'permissoes', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('admin_geral', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativas_falhas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('edicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('valor_cesta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_festa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidade_id', 'ano', name='uq_edicoes_cidade_ano')
    )
    op.create_index(op.f('ix_edicoes_cidade_id'), 'edicoes', ['cidade_id'], unique=False)
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('responsavel', sa.String(length=160), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidade_id', 'nome', name='uq_instituicoes_cidade_nome')
    )
    op.create_index(op.f('ix_instituicoes_cidade_id'), 'instituicoes', ['cidade_id'], unique=False)
    op.create_table('log_atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('tabela', sa.String(length=60), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_atividades_acao'), 'log_atividades', ['acao'], unique=False)
    op.create_index(op.f('ix_log_atividades_usuario_id'), 'log_atividades', ['usuario_id'], unique=False)
    op.create_table('perfil_permissoes',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id')
    )
    op.create_table('tokens_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo IN ('primeiro_acesso', 'redefinir_senha')", name='ck_tokens_acesso_tipo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_acesso_token_hash'), 'tokens_acesso', ['token_hash'], unique=False)
    op.create_index(op.f('ix_tokens_acesso_usuario_id'), 'tokens_acesso', ['usuario_id'], unique=False)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fornecedor', sa.String(length=180), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='ck_compras_quantidade'),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_categoria'), 'compras', ['categoria'], unique=False)
    op.create_index(op.f('ix_compras_edicao_id'), 'compras', ['edicao_id'], unique=False)
    op.create_table('dias_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dias_evento_edicao_id'), 'dias_evento', ['edicao_id'], unique=False)
    op.create_table('padrinhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_padrinhos_edicao_id'), 'padrinhos', ['edicao_id'], unique=False)
    op.create_index(op.f('ix_padrinhos_nome'), 'padrinhos', ['nome'], unique=False)
    op.create_index(op.f('ix_padrinhos_whatsapp'), 'padrinhos', ['whatsapp'], unique=False)
    op.create_table('usuario_edicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'edicao_id', name='uq_usuario_edicao')
    )
    op.create_index(op.f('ix_usuario_edicao_edicao_id'), 'usuario_edicao', ['edicao_id'], unique=False)
    op.create_index(op.f('ix_usuario_edicao_usuario_id'), 'usuario_edicao', ['usuario_id'], unique=False)
    op.create_table('criancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('dia_evento_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('checkin_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkin_por', sa.Integer(), nullable=True),
    sa.CheckConstraint("sexo IN ('M', 'F')", name='ck_criancas_sexo'),
    sa.CheckConstraint('idade >= 0 AND idade <= 21', name='ck_criancas_idade'),
    sa.ForeignKeyConstraint(['checkin_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dia_evento_id'], ['dias_evento.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edicao_id', 'instituicao_id', 'codigo', name='uq_criancas_edicao_inst_codigo')
    )
    op.create_index(op.f('ix_criancas_codigo'), 'criancas', ['codigo'], unique=False)
    op.create_index(op.f('ix_criancas_dia_evento_id'), 'criancas', ['dia_evento_id'], unique=False)
    op.create_index(op.f('ix_criancas_edicao_id'), 'criancas', ['edicao_id'], unique=False)
    op.create_index(op.f('ix_criancas_instituicao_id'), 'criancas', ['instituicao_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('padrinho_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('forma', sa.String(length=40), nullable=True),
    sa.Column('comprovante_arquivo', sa.String(length=500), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('conferido', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['padrinho_id'], ['padrinhos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_padrinho_id'), 'pagamentos', ['padrinho_id'], unique=False)
    op.create_table('usuario_instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_edicao_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_edicao_id'], ['usuario_edicao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_edicao_id', 'instituicao_id', name='uq_usuario_instituicao')
    )
    op.create_index(op.f('ix_usuario_instituicao_instituicao_id'), 'usuario_instituicao', ['instituicao_id'], unique=False)
    op.create_index(op.f('ix_usuario_instituicao_usuario_edicao_id'), 'usuario_instituicao', ['usuario_edicao_id'], unique=False)
    op.create_table('apadrinhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianca_id', sa.Integer(), nullable=False),
    sa.Column('padrinho_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=True),
    sa.Column('comissario_id', sa.Integer(), nullable=True),
    sa.Column('vai_ao_evento', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('cesta', 'festa')", name='ck_apadrinhamentos_tipo'),
    sa.ForeignKeyConstraint(['comissario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crianca_id'], ['criancas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['padrinho_id'], ['padrinhos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianca_id', 'tipo', name='uq_apadrinhamentos_crianca_tipo')
    )
    op.create_index(op.f('ix_apadrinhamentos_crianca_id'), 'apadrinhamentos', ['crianca_id'], unique=False)
    op.create_index(op.f('ix_apadrinhamentos_padrinho_id'), 'apadrinhamentos', ['padrinho_id'], unique=False)
    op.create_index(op.f('ix_apadrinhamentos_pagamento_id'), 'apadrinhamentos', ['pagamento_id'], unique=False)
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianca_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('arquivo', sa.String(length=500), nullable=False),
    sa.Column('texto_ocr', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'digitalizado'"), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('enviado_por', sa.Integer(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('digitalizado', 'enviado')", name='ck_cartoes_status'),
    sa.CheckConstraint("tipo IN ('cesta', 'festa')", name='ck_cartoes_tipo'),
    sa.ForeignKeyConstraint(['crianca_id'], ['criancas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianca_id', 'tipo', name='uq_cartoes_crianca_tipo')
    )
    op.create_index(op.f('ix_cartoes_crianca_id'), 'cartoes', ['crianca_id'], unique=False)
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianca_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pendente'"), nullable=False),
    sa.Column('entregue_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entregue_por', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pendente', 'montado', 'entregue')", name='ck_kits_status'),
    sa.ForeignKeyConstraint(['crianca_id'], ['criancas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entregue_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crianca_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kits')
    op.drop_index(op.f('ix_cartoes_crianca_id'), table_name='cartoes')
    op.drop_table('cartoes')
    op.drop_index(op.f('ix_apadrinhamentos_pagamento_id'), table_name='apadrinhamentos')
    op.drop_index(op.f('ix_apadrinhamentos_padrinho_id'), table_name='apadrinhamentos')
    op.drop_index(op.f('ix_apadrinhamentos_crianca_id'), table_name='apadrinhamentos')
    op.drop_table('apadrinhamentos')
    op.drop_index(op.f('ix_usuario_instituicao_usuario_edicao_id'), table_name='usuario_instituicao')
    op.drop_index(op.f('ix_usuario_instituicao_instituicao_id'), table_name='usuario_instituicao')
    op.drop_table('usuario_instituicao')
    op.drop_index(op.f('ix_pagamentos_padrinho_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_criancas_instituicao_id'), table_name='criancas')
    op.drop_index(op.f('ix_criancas_edicao_id'), table_name='criancas')
    op.drop_index(op.f('ix_criancas_dia_evento_id'), table_name='criancas')
    op.drop_index(op.f('ix_criancas_codigo'), table_name='criancas')
    op.drop_table('criancas')
    op.drop_index(op.f('ix_usuario_edicao_usuario_id'), table_name='usuario_edicao')
    op.drop_index(op.f('ix_usuario_edicao_edicao_id'), table_name='usuario_edicao')
    op.drop_table('usuario_edicao')
    op.drop_index(op.f('ix_padrinhos_whatsapp'), table_name='padrinhos')
    op.drop_index(op.f('ix_padrinhos_nome'), table_name='padrinhos')
    op.drop_index(op.f('ix_padrinhos_edicao_id'), table_name='padrinhos')
    op.drop_table('padrinhos')
    op.drop_index(op.f('ix_dias_evento_edicao_id'), table_name='dias_evento')
    op.drop_table('dias_evento')
    op.drop_index(op.f('ix_compras_edicao_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_categoria'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_tokens_acesso_usuario_id'), table_name='tokens_acesso')
    op.drop_index(op.f('ix_tokens_acesso_token_hash'), table_name='tokens_acesso')
    op.drop_table('tokens_acesso')
    op.drop_table('perfil_permissoes')
    op.drop_index(op.f('ix_log_atividades_usuario_id'), table_name='log_atividades')
    op.drop_index(op.f('ix_log_atividades_acao'), table_name='log_atividades')
    op.drop_table('log_atividades')
    op.drop_index(op.f('ix_instituicoes_cidade_id'), table_name='instituicoes')
    op.drop_table('instituicoes')
    op.drop_index(op.f('ix_edicoes_cidade_id'), table_name='edicoes')
    op.drop_table('edicoes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_permissoes_codigo'), table_name='permissoes')
    op.drop_table('permissoes')
    op.drop_table('perfis')
    op.drop_table('cidades')
    # ### end Alembic commands ###
