"""sessoes revogadas

Revision ID: 761f69d279cd
Revises: 5ab620c1b4d4
Create Date: 2026-09-23 09:37:34.319121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761f69d279cd'
down_revision: Union[str, Sequence[str], None] = '5ab620c1b4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_revogadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('revogada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_revogadas_expira_em'), 'sessoes_revogadas', ['expira_em'], unique=False)
    op.create_index(op.f('ix_sessoes_revogadas_jti'), 'sessoes_revogadas', ['jti'], unique=True)
    op.create_index(op.f('ix_sessoes_revogadas_usuario_id'), 'sessoes_revogadas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_revogadas_usuario_id'), table_name='sessoes_revogadas')
    op.drop_index(op.f('ix_sessoes_revogadas_jti'), table_name='sessoes_revogadas')
    op.drop_index(op.f('ix_sessoes_revogadas_expira_em'), table_name='sessoes_revogadas')
    op.drop_table('sessoes_revogadas')
    # ### end Alembic commands ###
