"""dia por instituicao

Revision ID: 83ef4dd6503b
Revises: da11e5950b86
Create Date: 2026-09-23 18:01:00.963843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ef4dd6503b'
down_revision: Union[str, Sequence[str], None] = 'da11e5950b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicao_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('dia_evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dia_evento_id'], ['dias_evento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edicao_id', 'instituicao_id', name='uq_instituicao_dia')
    )
    op.create_index(op.f('ix_instituicao_dia_dia_evento_id'), 'instituicao_dia', ['dia_evento_id'], unique=False)
    op.create_index(op.f('ix_instituicao_dia_edicao_id'), 'instituicao_dia', ['edicao_id'], unique=False)
    op.create_index(op.f('ix_instituicao_dia_instituicao_id'), 'instituicao_dia', ['instituicao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instituicao_dia_instituicao_id'), table_name='instituicao_dia')
    op.drop_index(op.f('ix_instituicao_dia_edicao_id'), table_name='instituicao_dia')
    op.drop_index(op.f('ix_instituicao_dia_dia_evento_id'), table_name='instituicao_dia')
    op.drop_table('instituicao_dia')
    # ### end Alembic commands ###
