"""envios do cartao de agradecimento

Revision ID: d1d4cbe74be4
Revises: c6cfdaa94956
Create Date: 2026-09-24 18:45:24.268332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d4cbe74be4'
down_revision: Union[str, Sequence[str], None] = 'c6cfdaa94956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envios_cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apadrinhamento_id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('mensagem_id', sa.String(length=120), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviado_por', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('enviado', 'falhou')", name='ck_envios_cartao_status'),
    sa.ForeignKeyConstraint(['apadrinhamento_id'], ['apadrinhamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envios_cartao_apadrinhamento_id'), 'envios_cartao', ['apadrinhamento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envios_cartao_apadrinhamento_id'), table_name='envios_cartao')
    op.drop_table('envios_cartao')
    # ### end Alembic commands ###
