"""sigla da instituicao

Revision ID: da11e5950b86
Revises: 761f69d279cd
Create Date: 2026-09-23 17:42:52.616284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da11e5950b86'
down_revision: Union[str, Sequence[str], None] = '761f69d279cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instituicoes', sa.Column('sigla', sa.String(length=6), nullable=True))
    op.create_unique_constraint('uq_instituicoes_cidade_sigla', 'instituicoes', ['cidade_id', 'sigla'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_instituicoes_cidade_sigla', 'instituicoes', type_='unique')
    op.drop_column('instituicoes', 'sigla')
    # ### end Alembic commands ###
